charts/pgadmin4/README.md, charts/pgadmin4/templates/_helpers.tpl, charts/pgadmin4/templates/deployment.yaml, charts/pgadmin4/templates/networkpolicy.yaml, charts/pgadmin4/templates/secrets.yaml, charts/pgadmin4/templates/service.yaml, charts/pgadmin4/values.yaml
Hi,
Here are various improvements for your chart that we needed to get it running in our environment with restricted network policy, together with an authentication sidecar proxy and pre-generated secret files.
I hope you'll find these changes useful, that they can be merged
=> Pgadmin4 chart improvements

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/templates/deployment.yaml, charts/pgadmin4/values.yaml
Add podAnnoations support in deployment template
- fixes #
=> [pgadmin4] Add podAnnotations support

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/values.yaml
Use current latest released app by default.
=> [pgadmin4] Deploy latest available pgAdmin version 4.20

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/values.yaml
=> [pgadmin4] Fix ingress params in README and values

charts/pgadmin4/Chart.yaml, charts/pgadmin4/templates/deployment.yaml, charts/pgadmin4/values.yaml
Adds support fot cusom environment variables in pgadmin deployment.
- fixes #9 
=> [pgadmin4] Add support for custom environment variables

charts/pgadmin4/Chart.yaml, charts/pgadmin4/templates/deployment.yaml
=> Removed excessive -name within extraInitContainers

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/values.yaml
=> pgadmin4 upgrade from 4.21 to 4.22

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/examples/add-pgpass-file.yaml, charts/pgadmin4/examples/ingress-with-outside-tls-termination.yaml, charts/pgadmin4/examples/set-admin-creds.yaml, charts/pgadmin4/values.yaml
Some part of configuration not fully documented or have mistakes which greatly complicates the work with the chart for newbies. This PR try fix part of this.
=> [pgadmin4] Improve examples

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/values.yaml
=> upgrade from 4.22 to 4.23

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/values.yaml
=> version upgrade from 4.23 to 4.24

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/templates/pvc.yaml, charts/pgadmin4/values.yaml
Also resolved spelling mistake within templates/pvc.yaml
=> version upgrade from 4.24 to 4.25

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/values.yaml
=> update from 4.25 to 4.26

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/templates/networkpolicy.yaml, charts/pgadmin4/values.yaml
Signed-off-by: kahootali <kahoot.ali@gmail.com>
This PR adds the field to enable or disable NetworkPolicy
- fixes #48 
=> [pgadmin4] add field to configure network policy

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/values.yaml
=> version upgrade from 4.26 to 4.27

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md
Fixes some helm commands in the README.
=> fix(pgadmin4): helm install usage

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/values.yaml
=> version upgrade from 4.27 to 4.28

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/values.yaml
=> pgadmin4 upgrade from 4.28 to 4.29

.github/PULL_REQUEST_TEMPLATE.md, .github/stale.yml, .github/workflows/codespell.yaml, .github/workflows/lint-test.yaml, ct.yaml
=> minor adjustment to the testing workflow

charts/pgadmin4/Chart.yaml, charts/pgadmin4/templates/tests/test-connection.yaml
=> [pgadmin4] Remove readOnlyRootFileSystem=true in test-connection.yaml

charts/pgadmin4/Chart.yaml, charts/pgadmin4/templates/tests/test-connection.yaml
This fix will enable `Lint and test chart` workflow passed (Current failure of `test-connection` is caused by #63).
This fix is complete (vs. last PR #70, which should not be merged, sorry for the trouble)  and verified in a microk8s cluster. 
- fixes #
=> [pgadmin4] Fix test-connection to avoid writing to filesystem

charts/pgadmin4/Chart.yaml, charts/pgadmin4/values.yaml
=> pgadmin4 upgrade to 4.30 from 4.29

charts/pgadmin4/Chart.yaml, charts/pgadmin4/templates/deployment.yaml, charts/pgadmin4/values.yaml
https://www.pgadmin.org/docs/pgadmin4/development/release_notes_5_0.html
=> pgadmin4 upgrade to 5.0 from 4.30

README.md, charts/pgadmin4/Chart.yaml
Issue: https://github.com/rowanruseler/helm-charts/issues/78
=> remove ending / at runix.net by helm add

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md
Forgot to also remove in within the chart README.md itself
=> remove ending / at runix.net by helm add repo

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/templates/_helpers.tpl, charts/pgadmin4/templates/deployment.yaml, charts/pgadmin4/templates/service.yaml
Added in:
* deployment.yaml
* service.yaml
=> selector Labels _helpers.tpl

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/templates/hpa.yaml, charts/pgadmin4/values.yaml
=> Horizontal Pod Autoscaler

charts/pgadmin4/Chart.yaml, charts/pgadmin4/templates/deployment.yaml
ServiceAccount mapping to Deployment failed.
- fixes #
=> [pgadmin4] Bugifx: serviceAccount creation

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md
=> added existingClaims to README.md

charts/pgadmin4/Chart.yaml, charts/pgadmin4/values.yaml
See the official release notes here:
https://www.pgadmin.org/docs/pgadmin4/development/release_notes_5_1.html#version-5-1
=> pgadmin4 upgrade from 5.0 to 5.1

charts/pgadmin4/Chart.yaml, charts/pgadmin4/templates/NOTES.txt
previously:
```
NOTES:
1. Get the application URL by running these commands:
https://test.example.commap[path:/]
```
after this commit:
```
NOTES:
1. Get the application URL by running these commands:
https://test.example.com/
```
=> NOTES is creating an unusable link

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/templates/deployment.yaml, charts/pgadmin4/values.yaml
I need provision to add   custom labels in pod, hence creating this simple MR.
=> [pgadmin4] support for pod labels

.github/workflows/lint-test.yaml, charts/pgadmin4/Chart.yaml, charts/pgadmin4/templates/ingress.yaml, charts/pgadmin4/values.yaml
Should resolve: https://github.com/rowanruseler/helm-charts/issues/93
I did not yet test this
=> implementation of v1.18+ and v1.19+ for ingress

charts/pgadmin4/Chart.yaml, charts/pgadmin4/values.yaml
=> upgrade from 5.1 to 5.2

charts/pgadmin4/Chart.yaml, charts/pgadmin4/values.yaml
=> version upgrade to 5.3

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/values.yaml
https://www.pgadmin.org/docs/pgadmin4/5.4/release_notes_5_4.html
=> version upgrade to 5.4

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/values.yaml
=> version upgrade from 5.4 to 5.5

.github/workflows/lint-test.yaml, charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/values.yaml, kind-config.yaml
=> version upgrade from 5.5 to 5.6

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/values.yaml
=> version upgrade from 5.6 to 5.7

charts/pgadmin4/Chart.yaml, charts/pgadmin4/examples/enable-ldap-integration.yaml
Add an example to show to properly set up PGAdmin with an AD domain
=> [pgadmin4] Add example enable LDAP integration

charts/pgadmin4/Chart.yaml, charts/pgadmin4/templates/tests/test-connection.yaml
We don't need the pod to be hanging out and introducing noises in the cluster. If it fails, then retain the pod else delete the pod on a successful completion.
- fixes #
**n/a**
=> [pgadmin4] Clean up test pod after running helm test

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/templates/_helpers.tpl, charts/pgadmin4/templates/deployment.yaml, charts/pgadmin4/values.yaml
includes default Chart.AppVersion as Values.image.tag
=> version upgrade from 5.7 to 6

charts/pgadmin4/Chart.yaml
=> version upgrade from 6 to 6.1

charts/pgadmin4/Chart.yaml
https://www.pgadmin.org/docs/pgadmin4/6.2/release_notes_6_2.html
=> version upgrade from 6.1 to 6.2

charts/pgadmin4/Chart.yaml
https://www.pgadmin.org/docs/pgadmin4/development/release_notes_6_4.html
=> version upgrade from 6.3 to 6.4

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md
=> fixing small typos

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md
https://www.pgadmin.org/docs/pgadmin4/6.5/release_notes_6_5.html
=> version upgrade from 6.4 to 6.5

charts/pgadmin4/Chart.yaml
https://www.pgadmin.org/docs/pgadmin4/6.6/release_notes_6_6.html
=> version upgrade from 6.5 to 6.6

charts/pgadmin4/Chart.yaml, charts/pgadmin4/templates/deployment.yaml, charts/pgadmin4/values.yaml
Signed-off-by: Matthias Mai <eineschnapsidee@gmail.com>
Adds support for additional custom volumes and volumeMounts to the deployment
- fixes #140
=> [pgadmin4] add support for extra volumes and volumeMounts

charts/pgadmin4/Chart.yaml
https://pgadmin.org/docs/pgadmin4/6.7/release_notes_6_7.html
=> version upgrade from 6.6 to 6.7

charts/pgadmin4/Chart.yaml, charts/pgadmin4/examples/add-oauth2-config.yaml
Version upgrade from 6.7 to 6.8: https://www.pgadmin.org/docs/pgadmin4/6.8/release_notes_6_8.html
Also included a minor fix for an example: https://github.com/rowanruseler/helm-charts/issues/145
=> version upgrade from 6.7 to 6.8

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/templates/deployment.yaml, charts/pgadmin4/values.yaml
Version upgrade from 6.8 to 6.9: pgadmin.org/docs/pgadmin4/6.8/release_notes_6_9.html
and added priorityClassName as requested in https://github.com/rowanruseler/helm-charts/issues/151
=> version upgrade from 6.8 to 6.9 and priorityClassName

charts/pgadmin4/Chart.yaml
version upgrade from 6.9 to 6.10: https://www.pgadmin.org/docs/pgadmin4/6.10/release_notes_6_10.html
=> version upgrade from 6.9 to 6.10

charts/pgadmin4/Chart.yaml
fixes: https://github.com/rowanruseler/helm-charts/issues/156
=> quote version number

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/values.yaml
It allows us to keep existed secrets without changes
- fixes #166 
Details is in the PR #164 
=> [pgadmin4] Allows us to keep existed secrets without changes for release 1.12.0 and fixes #166

charts/pgadmin4/Chart.yaml, charts/pgadmin4/examples/add-oauth2-config.yaml
Just example to the user, how to get OAUTH2_CLIENT_ID and OAUTH2_CLIENT_SECRET from environment.
=> [pgadmin4] Get OAUTH2_CLIENT_ID and OAUTH2_CLIENT_SECRET from environment

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/templates/service.yaml, charts/pgadmin4/values.yaml
Signed-off-by: LedAlex <mazafaka1@mail.ru>
- fixes #
=> [pgadmin4] Load Balancer IP Support (fixes #173)

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/values.yaml
- 161
This MR fixes the problem - old one default username `chart@domain.com` does not allow to login.
=> [pgadmin4] Default username change to chart@domain.com

charts/pgadmin4/Chart.yaml, charts/pgadmin4/examples/add-oauth2-config.yaml
=> [pgadmin4] Typo in add-oauth2-config.yaml example

charts/pgadmin4/Chart.yaml
Install [latest release of pgadmin](https://www.pgadmin.org/docs/pgadmin4/latest/release_notes.html) 6.15
=> [pgadmin4] upgrade to pgadmin 6.15

charts/pgadmin4/Chart.yaml
Install [latest tag of pgadmin](https://github.com/pgadmin-org/pgadmin4/tagsl) 6.16
=> [pgadmin4] upgrade to pgadmin 6.16

charts/pgadmin4/Chart.yaml
Install [latest release of pgadmin](https://www.pgadmin.org/docs/pgadmin4/latest/release_notes.html) 6.17 with [these changes](https://github.com/pgadmin-org/pgadmin4/compare/REL-6_16...REL-6_17).
=> [pgadmin4] upgrade to pgadmin 6.17

charts/pgadmin4/Chart.yaml
Install [latest release of pgadmin](https://www.pgadmin.org/docs/pgadmin4/latest/release_notes.html) 6.18 with [these changes](https://github.com/pgadmin-org/pgadmin4/compare/REL-6_17...REL-6_18) and these [release notes](https://www.pgadmin.org/docs/pgadmin4/latest/release_notes_6_18.html).
=> [pgadmin4] upgrade to pgadmin 6.18

charts/pgadmin4/Chart.yaml
ref: https://www.pgadmin.org/docs/pgadmin4/6.19/release_notes_6_19.html
=> [pgadmin4] version upgrade from 6.18 to 6.19

charts/pgadmin4/Chart.yaml, charts/pgadmin4/examples/enable-ldap-integration.yaml, charts/pgadmin4/examples/ingress-with-outside-tls-termination.yaml, charts/pgadmin4/templates/ingress.yaml
use proper path for context
- fixes #191
- fixes hosts path in `examples/enable-ldap-integration` and `examples/ingress-with-outside-tls-termination.yaml`
=> [pgadmin4] fix: ingress tls .secretName check

charts/pgadmin4/Chart.yaml
Install [latest release of pgadmin](https://www.pgadmin.org/docs/pgadmin4/latest/release_notes.html) 6.20 with [these changes](https://github.com/pgadmin-org/pgadmin4/compare/REL-6_19...REL-6_20) and these [release notes](https://www.pgadmin.org/docs/pgadmin4/latest/release_notes_6_20.html).
=> [pgadmin4] upgrade to pgadmin 6.20

charts/pgadmin4/Chart.yaml
Install [latest release of pgadmin](https://www.pgadmin.org/docs/pgadmin4/latest/release_notes.html) 6.21 with [these changes](https://github.com/pgadmin-org/pgadmin4/compare/REL-6_20...REL-6_21) and these [release notes](https://www.pgadmin.org/docs/pgadmin4/latest/release_notes_6_21.html).
=> [pgadmin4] upgrade to pgadmin 6.21

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/templates/extra-list.yaml, charts/pgadmin4/values.yaml
need it to deploy a service of type ExternalName
=> [pgadmin4] added extray deploy to deploy extra ressources

charts/pgadmin4/Chart.yaml, charts/pgadmin4/templates/deployment.yaml
This is so that when overriding the entry point, different args can be passed in
- fixes #
=> Add args to deployment template

charts/pgadmin4/Chart.yaml, charts/pgadmin4/examples/add-oauth2-config.yaml
After spending too much time on the internet gathering various outdated sources I've made a working copy of Microsoft Azure AD OAuth integration.
While at it, I also changed configuration to use ConfigMap and move only sensitive part to Secret.
=> [pgadmin4] Add Microsoft Azure AD OAuth example

charts/pgadmin4/Chart.yaml
Upgrades to the latest version of  pgadmin for bug fixes.
=> chore: bump pgadmin version to 7.3

charts/pgadmin4/Chart.yaml
=> [pgadmin4] Bump pgadmin version to 7.4

charts/pgadmin4/Chart.yaml
ref: https://www.pgadmin.org/docs/pgadmin4/7.5/release_notes_7_5.html
=> [pgadmin4] upgrade from 7.4 to 7.5

charts/pgadmin4/Chart.yaml, charts/pgadmin4/examples/add-oauth2-config.yaml, charts/pgadmin4/templates/deployment.yaml
fixes configmap not found error:
```
Error: UPGRADE FAILED: cannot patch "pgadmin-pgadmin4" with kind Deployment: Deployment.apps "pgadmin-pgadmin4" is invalid: [spec.template.spec.volumes[1].configMap.name: Required value, spec.template.spec.containers[0].volumeMounts[1].name: Not found: "config-local"]
```
=> fix oauth2 configmap not found issue

charts/pgadmin4/Chart.yaml
ref: https://www.pgadmin.org/docs/pgadmin4/7.6/release_notes_7_6.html
=> [pgadmin4] upgrade from 7.5 to 7.6

charts/pgadmin4/Chart.yaml
ref: https://www.pgadmin.org/docs/pgadmin4/7.7/release_notes_7_7.html
=> [pgadmin4] upgrade from 7.6 to 7.7

charts/pgadmin4/Chart.yaml
Updates pgadmin4 container version from 7.7 to 7.8. With 7.7 we faced a [binary path issue](https://github.com/pgadmin-org/pgadmin4/issues/6882) and it longer is present if 7.8 is used.
=> [pgadmin4] Update to 7.8

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/templates/deployment.yaml, charts/pgadmin4/values.yaml
Allows reusing existing PVC's. More details in the linked issue.
- fixes #228 
- [ x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ x ] Chart Version bumped
- [ x ] Variables are documented in the README.md
- [ x ] Title of the PR starts with chart name (e.g. `[pgadmin4]`)
=> [pgadmin4] Added subPath to persistentVolume in deployment.yaml

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/templates/_helpers.tpl, charts/pgadmin4/templates/deployment.yaml, charts/pgadmin4/values.yaml
=> [pgadmin4] common labels

charts/pgadmin4/Chart.yaml
Upgrades pgadmin4 container version from 8.1 to 8.2
https://www.pgadmin.org/docs/pgadmin4/8.2/release_notes_8_2.html
=> [pgadmin4] upgrade to pgadmin 8.2

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md
Small README.md update, resolves issue #224
=> Fixes issues 244

charts/pgadmin4/Chart.yaml
ref 8.9: pgadmin.org/docs/pgadmin4/8.9/release_notes_8_9.html
=> [pgadmin4] upgrade from 8.8 to 8.9

charts/pgadmin4/Chart.yaml
ref 8.10: pgadmin.org/docs/pgadmin4/8.10/release_notes_8_10.html
=> [pgadmin4] upgrade from 8.9 to 8.10

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/templates/deployment.yaml, charts/pgadmin4/values.yaml
Signed-off-by: adnanm syedmadnan02@gmail.com
- fixes #259
=> [pgadmin4] feat: added dnsPolicy and dnsConfig templates

charts/pgadmin4/Chart.yaml
This update of pgAdmin4 fixes [CVE-2024-9014](https://nvd.nist.gov/vuln/detail/CVE-2024-9014)
none
- [] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
=> [pgadmin4] upgrade from 8.11 to 8.12

charts/pgadmin4/Chart.yaml, charts/pgadmin4/templates/_helpers.tpl
Fixes:
* https://github.com/rowanruseler/helm-charts/issues/241
=> [pgadmin4] Quote namespace for numeric names

charts/pgadmin4/Chart.yaml
ref 8.14: pgadmin.org/docs/pgadmin4/8.14/release_notes_8_14.html
=> [pgadmin4] upgrade from 8.13 to 8.14

.github/workflows/lint-test.yaml, charts/pgadmin4/Chart.yaml
ref 9.0: pgadmin.org/docs/pgadmin4/9.0/release_notes_9_0.html
=> [pgadmin4] upgrade from 8.14 to 9.0

charts/pgadmin4/Chart.yaml
ref 9.1: pgadmin.org/docs/pgadmin4/9.1/release_notes_9_1.html
=> [pgadmin4] upgrade from 9.0 to 9.1

charts/pgadmin4/Chart.yaml
ref 9.2: pgadmin.org/docs/pgadmin4/9.2/release_notes_9_2.html
=> [pgadmin4] upgrade from 9.1 to 9.2

charts/pgadmin4/Chart.yaml, charts/pgadmin4/templates/deployment.yaml
This commit should fix: https://github.com/rowanruseler/helm-charts/issues/279
=> fix(pgadmin4): correct typo from 'hostname' to 'hostnames'

charts/pgadmin4/Chart.yaml, charts/pgadmin4/templates/ingress.yaml
Correct value is: pathType: {{ .pathType }}
=> fix(pgadmin4): fixing pathType

charts/pgadmin4/Chart.yaml
Release date: 2025-04-30
This release contains a number of bug fixes and new features since the release of pgAdmin 4 v9.2.
ref: http://pgadmin.org/docs/pgadmin4/9.3/release_notes_9_3.html
=> [pgadmin4] upgrade from 9.2 to 9.3

charts/pgadmin4/Chart.yaml, charts/pgadmin4/templates/_helpers.tpl, charts/pgadmin4/templates/deployment.yaml, charts/pgadmin4/templates/ingress.yaml, charts/pgadmin4/templates/pvc.yaml, charts/pgadmin4/templates/service.yaml, charts/pgadmin4/templates/serviceaccount.yaml, charts/pgadmin4/values.yaml
[pgadmin4]
Added new function tplToMap
fixed typos
new function allows tpl in annotations and labels
Edited resources to match the new function
Minor Version Bump.
=> [pgadmin4] Added new function tplToMap, fixed typos, allows tpl in annotations and labels

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/templates/tests/test-connection.yaml
Ran into a small issue after merging https://github.com/rowanruseler/helm-charts/pull/309, this commit fixes and adds a small description to readme.md.
=> [pgadmin4] minor fix for test enabled

charts/pgadmin4/Chart.yaml, charts/pgadmin4/README.md, charts/pgadmin4/templates/deployment.yaml, charts/pgadmin4/templates/preferences-configmap.yaml, charts/pgadmin4/values.yaml
Feature lets you customize the preferences of the pgadmin deployment before initialization. pretty similar feature to pre loading server definitions.
Docs: https://www.pgadmin.org/docs/pgadmin4/latest/preferences.html
=> [pgadmin4] New predefined preferences feature

charts/pgadmin4/Chart.yaml
Release date: 2025-07-1
This release contains a number of bug fixes and new features since the release of pgAdmin 4 v9.4.
ref: https://www.pgadmin.org/docs/pgadmin4/9.5/release_notes_9_5.html
=> [pgadmin4] upgrade from 9.4 to 9.5

charts/pgadmin4/Chart.yaml
Release date: 2025-07-25
This release contains a number of bug fixes and new features since the release of pgAdmin 4 v9.5.
ref: https://www.pgadmin.org/docs/pgadmin4/9.6/release_notes_9_6.html
=> [pgadmin4] upgrade from 9.5 to 9.6

charts/pgadmin4/Chart.yaml
Release date: 2025-09-04
This release contains a number of bug fixes and new features since the release of pgAdmin 4 v9.7.
ref: https://www.pgadmin.org/docs/pgadmin4/9.8/release_notes_9_8.html
=> [pgadmin4] upgrade from 9.7 to 9.8
