- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/deployment.yaml
It adds support for the following objects that I needed to read data from kubernetes secrets:
- extraInitContainers
- extraSecretMounts
Additionally I added the possiblilty to set the PGPASSFILE environment variable. This is also needed to read password from a kubernetes secret.
- [x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x ] Chart Version bumped
- [x ] Variables are documented in the README.md
- [x ] Title of the PR starts with chart name (e.g. `[mychartname]`)
> [mytracks/pgadmin-helm-chart] Support for kubernetes secrets

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/templates/deployment.yaml
It fixes a mispelling of imagePullSecrets.
Before in order to define an imagePullSecret to pull the image we had to define two variables :
- imagePullSecrets
- iamgePullSecrets
Renaming iamgePullSecrets to imagePullSecrets solves this.
> [runix/pgadmin4] fix: fix mispelling value imagePullSecrets

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/deployment.yaml
- charts/pgadmin4/values.yaml
VolumePermissions:
Pre the release of version 4.16, volume permissions had to be adjusted
or pgAdmin4 would error out on:
* PermissionError: [Errno 13] Permission denied: '/var/log/pgadmin'
By default it is now disabled, since version 4.16 and up it will show
a warning and functions without the permissions adjustment.
ExtraInitContainers:
This value was already added in the templates/deployment but never
documentated nor added in the values.yaml file.
> initContainers, volume permissions and extra init

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/values.yaml
Adjusted the version from 4.20 toward 4.21, and adjusted some links that
had previous version release documentation to `latest`.
Also updated the Chart.yaml with keywords and icon for Helm Hub.
> version upgrade from 4.20 to 4.21

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/templates/networkpolicy.yaml
Network policies should be applied for container ports, rather than service ports. Service ports can be different than container ports.
> [pgadmin4]: Use correct port in network policy

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/values.yaml
It looks like that previously used proxy redirect rule for ingress no longer works for new pgAdmin version `4.21`, causing the application to ignore custom URL path right after logging in.
This PR fixes regex to ensure correct behavior.
> [pgadmin4] Update ingress example to match version `4.21`

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/templates/deployment.yaml
Previously !!string was used, this has to be either !!str or we can just
quote it with the Go templates.
Go tempaltes: https://helm.sh/docs/howto/charts_tips_and_tricks/
Appendix: https://helm.sh/docs/chart_template_guide/yaml_techniques/
> template adjustment enhanced_cookie_protection

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/values.yaml
This PR updates Ingress configuration example to work with version 4.22 of pgAdmin.
It covers the http:// to https:// redirection when relative URL path is used.
It also makes login in to pgAdmin working if only https is allowed for Ingress.
> [pgadmin4] Fix HTTPS URL relative path redirects for v4.22

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/templates/deployment.yaml
Currently, installing the chart fails in case of integer values in additional environment variables.
The Issue raised for this feature included a example which is mostly followed, except the quotation [1].
Added this.
Usually ints don't need to be quoted, except in environment vars [2].
[1]: https://github.com/helm/charts/blob/f2fcadaa5a1af57bbdf2e49a99f25c9589d5b540/stable/fluentd/templates/deployment.yaml#L68-L71
[2]: https://helm.sh/docs/howto/charts_tips_and_tricks/#quote-strings-dont-quote-integers
- fixes #
> [pgadmin4] Fix quoting for non-string environment variables

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/deployment.yaml
- charts/pgadmin4/values.yaml
Some clusters require that all the containers have `resources` section defined in order to start.
This PR allows to set resources for the init container.
> [pgadmin4] Add init.resources

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/templates/_helpers.tpl
When you specify `image.tag` different that specified in Chart.yaml, resource label `app.kubernetes.io/version` show wrong version.
https://github.com/rowanruseler/helm-charts/blob/301772b7c61dcb7a005769ffa9863583e0445eaa/charts/pgadmin4/templates/_helpers.tpl#L42
This PR fix this behavior.
- fixes #37 
> [pgadmin4] Fix hardcode pgAdmin version label

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/templates/_helpers.tpl
This PR corects the usage of newer API for NetworkPolicy object in modern Kubernetes version.
The [Kubernetes blog post](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) says that new `networking.k8s.io/v1` API version was available since v1.8.
Also fixed semver comparison for Helm v3 according to the docs:
https://helm.sh/docs/chart_template_guide/function_list/#semvercompare
> [pgadmin4] Fix definition of API for NetworkPolicy

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/deployment.yaml
- charts/pgadmin4/templates/tests/test-connection.yaml
- charts/pgadmin4/values.yaml
Allow user to use registry other than default `docker.io`.
- fixes #
Tested by importing pgadmin as subcharts manually.
> [charts/pgadmin4] Request to add image registry to values.yaml

- .ci/ct-config.yaml
helm has https://kubernetes-charts.storage.googleapis.com/index.yaml and
this no longer resolves. Adding the new repository
https://charts.helm.sh/stable
> new stable repo url

- .github/workflows/test.yaml
- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/deployment.yaml
- charts/pgadmin4/values.yaml
Implements "one-change" support for hosting pgadmin4 on a context path (e.g. mydomain.com/pgadmin).
Documentation on [pgadmin.org](https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html#http-via-nginx) demonstrates (sort of) how pgadmin4 can be hosted on a subdirectory/context path by adding the environment variable `SCRIPT_PATH`. However, since the request paths for the `readinessProbe` and `livenessProbe` are hard coded, modifications are needed to the helm chart to implement.
To make it more clear what this option does, I named the value field `contextPath`.
I have tested these modifications using `kustomize`, and have also verified that helm builds correctly with these modifications.
I'm not entirely certain whether placing this option underneath the environment …
> [pgadmin4] Add Support For Context Path Hosting

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/deployment.yaml
- charts/pgadmin4/templates/tests/test-connection.yaml
- charts/pgadmin4/values.yaml
1. Not include empty `initContainers:` in `deployment.yaml` when no extra initContainer or volumePermission is defined.
2. Add `test.resources` and `test.securityContext` to fix lint warnings.
3. Add `annotations` for Deployment. 
* Specifically, this allows adding `kube-linter` ignore-check annotations such as
```
apiVersion: apps/v1
kind: Deployment
metadata:
name: pg-pgadmin4
labels:
annotations:
ignore-check.kube-linter.io/no-read-only-root-fs: This deployment requires rw access
to root filesystem
```
- fixes #
> [pgadmin4] Fix deployment and test lint warnings

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/deployment.yaml
- charts/pgadmin4/templates/serviceaccount.yaml
- charts/pgadmin4/values.yaml
Adds a ServiceAccount resource.
Needed for using service communication ACLs. (e.g. [Consul ACL](https://www.consul.io/docs/k8s/connect#accepting-inbound-connections))
- fixes #
> [pgadmin4] Add ServiceAccount

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/values.yaml
Updated README.md
Set default vlaue of `serviceAccount.create` to `false`
-> Reason: ServiceAccount may not be needed by the broad user base
- fixes #
> [pgadmin4] UPDATE Create ServiceAccount

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/templates/_helpers.tpl
The Ingress api version should be `networking.k8s.io/v1` by default and fallback to `networking.k8s.io/v1beta1 ` if v1 is not supported.
- fixes #88 
> [pgadmin4] ingress api version should be v1 by default

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/templates/_helpers.tpl
- charts/pgadmin4/templates/ingress.yaml
- charts/pgadmin4/values.yaml
To not make this chart to complicated, or to estranged of how helm
itself dictates example. I've decided to revert the default apiVersion of
ingress back towards networking.k8s.io/v1beta1 and also still make
version extensions/v1beta1 available. Once helm itself makes the default
example adjustment to suit apiVersion networking.k8s.io/v1, this chart
will reflex that.
Until then, I will make sure future adjustment will not be easily
merged without further testing it.
Be aware that previous values.yaml configurations need to be adjusted to
match the default helm ingress example. Biggest adjustment is how paths
are defined.
Also cleaned up some comments in the values file, since the values file
feels to cluttered with examples for my taste.
Signed-off-by: Rowan Ruseler …
> default template/ingress and values

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/values.yaml
even thought it is an example, chances are higher that when a person
uses the example the chart version is actually set towards the latest
released version.
> adjusted the example image tag to latest

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/deployment.yaml
- charts/pgadmin4/values.yaml
Signed-off-by: Anselm Eberhardt <aeberhardt@dg-i.net>
Exposes the container port configuration as a variable. This makes it possible to use this chart with pgadmin containers which are not allowed to bind to low ports.
> [pgadmin4] Make container port configurable

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/examples/add-oauth2-config.yaml
From pgadmin 5.5 there is OAUTH2 configuration available so it would be cool if there is an example for that part. I set it up like this, so that there is no need to adjust chart templates for now.
It also works if these vars are set in `variables` section of values.yaml with adding prefix PGADMIN_CONFIG_ to those vars.
~~Also...still having issues with google auth, something with OAUTH2_API_BASE_URL so work in progress, but here it is and if it helps someone great!~~
> [pgadmin4] oauth2 example config

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/_helpers.tpl
- charts/pgadmin4/values.yaml
Previously the values.yaml file had to contain the serverDefinitions as
followed:
```
serverDefinitions:
servers: |-
"1": {
"Name": "Minimally Defined Server",
"Group": "Servers",
...
}
```
With this change, the following data structure is used:
```
serverDefinitions:
servers:
firstServer:
Name: "Minimally Defined Server"
Group: "Servers"
...
```
Be aware that this can break your current release, if upgrading to this
helm chart version 1.9.0.
This solution was brought to my attention by https://github.com/itscaro,
so thanks!
> serverDefinitions servers mapped instead of string

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/ingress.yaml
- charts/pgadmin4/values.yaml
Since Kubernetes 1.18 ([source](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/)) it is possbile to specify a `ingressClassName` on ingress resources, to specify which `IngressClass` should be used to handle the ingress. This allows for the Chart to generate an ingress resource for a specified `IngressClass`.
*None*
*None*
> [pgadmin4] Add support for ingressClassName to ingress resource

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/deployment.yaml
- charts/pgadmin4/values.yaml
Adds the ability to override container's default entrypoint.
Specifically useful when there's a need to source external environment variables but may also assist with different approaches people find useful.
- fixes #135 
> [pgadmin4] Ability to override container's default entrypoint

- .prettierignore
- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/deployment.yaml
- charts/pgadmin4/values.yaml
you can choose secret key now
Some users might have already created secrets with different key for pgadmin default password. For example official pgadmin4 docker image comes with key PGADMIN_DEFAULT_PASSWORD. Now we can pick a key name for password in our secret file instead of sticking to hardcoded 'password' key name.
> [pgadmin4] you can choose secret key now

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/deployment.yaml
- charts/pgadmin4/values.yaml
Signed-off-by: Cyril Jouve <jv.cyril@gmail.com>
- fixes #
```shell
helm template . > ref.yaml
helm template --set containerSecurityContext.enabled=true . > new.yaml
```
```diff
--- ref.yaml	2022-10-07 13:24:39.000000000 +0200
+++ new.yaml	2022-10-07 13:24:56.000000000 +0200
@@ -101,6 +101,8 @@
- name: pgadmin4
image: "docker.io/dpage/pgadmin4:6.14"
imagePullPolicy: IfNotPresent
+          securityContext:
+            allowPrivilegeEscalation: false
ports:
- name: http
containerPort: 80
```
> [pgadmin4] allow to override container securityContext

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/deployment.yaml
I need to add a startupProbe in my implementation because my deployment need too much time to inject all the configurations
- [x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x ] Chart Version bumped
- [x ] Variables are documented in the README.md
- [x ] Title of the PR starts with chart name (e.g. `[pgadmin4]`)
> [pgadmin4] added startupprobe to deployment

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/values.yaml
When using the chart and uncommenting the resource part of test container the chart deployment will fail.
Reason is that requests > limits
With this fix it is possible to just uncomment the resource part because request < limits
- fixes #
Thanks for this awesome chart! 
> [pgadmin4] fix: resource definition of test container

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/templates/ingress.yaml
Fix the case when `ingress.tls.secretName`, `ingress.tls.host` or `ingress.hosts` are a templated value (similar to this issue https://github.com/bitnami/charts/issues/13503).
> [pgadmin4] fix(ingress): make template resolution available for ingress secret name

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/auth-secret.yaml
- charts/pgadmin4/templates/deployment.yaml
- charts/pgadmin4/templates/secrets.yaml
- charts/pgadmin4/templates/server-definitions-configmap.yaml
- charts/pgadmin4/templates/server-definitions-secret.yaml
- charts/pgadmin4/values.yaml
Users might want to adapt `serverDefinitions` while still having the ability to pre-define a secret for the super user's password. This PR decouples the secret creation of `serverDefinitions` from the password's secret to keep them separate.
In addition, users can specify `serverDefinitions.resourceType` to deploy the configuration as either `ConfigMap` (default) or `Secret`.
- fixes #182 
> [pgadmin4] Decouple serverDefinitions from existingSecret

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/templates/server-definitions-secret.yaml
As reported in issue #216, the existingSecret is not respected with the new secret for server-definitions. This commit should resolve that.
> [pgadmin4] issue #216 existingSecret

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/templates/_helpers.tpl
This PR sets the `app.kubernetes.io/version` label to match real application version, which could be overridden by `image.tag` value.
Previously, the label did inherit only `appVersion` set in the chart metadata. Now if the image version (tag) is not set, the label will fallback to the app version defined by the chart.
> [pgadmin4] Set app version label to image tag

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/examples/add-oauth2-config.yaml
- charts/pgadmin4/templates/deployment.yaml
https://github.com/rowanruseler/helm-charts/pull/214 fixed incorrect OAuth2 example, however it produced two new unforeseen consequences:
1. The change is not backward compatible because if someone already had `extraConfigmapMounts` set they would need rename it (`config-local` -> `pgadmin4-config`) for the upgraded deployment to progress.
2. Example now actually uses `pgadmin4-config` as default volume name which could be pretty common to mount volumes for other configuration purposes. For example, me personally, I have used such name for a volume which stored `file.pgpass` file. So, in the end, I had to do some back and forth reconfiguration of my deployment in order to upgrade.
This PR brings back `config-local` as a volume name (which I think is more appropriate identicator for what …
> [pgadmin4] Fix accidental volume override

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/deployment.yaml
This PR adds the possibility to use template strings for "extraConfigmapMounts.[].configMap" and "extraSecretMounts.[].secret" if the ConfigMap / Secret has a dynamic name.
- fixes #230 
nothing special
> [pgadmin4] feat: add possibility to use template-strings inside values.yaml

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/examples/add-oauth2-config.yaml
OIDC allows to use server side claim filtering via information provided in the token. See https://learn.microsoft.com/en-us/security/zero-trust/develop/configure-tokens-group-claims-app-roles and pgAdmin documentation for more information.
This funcionality requires at least pgAdmin4 version 8.0.
> [pgadmin4] Add Microsoft OAuth example with OIDC support

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/deployment.yaml
- charts/pgadmin4/values.yaml
We use this chart as dependency (child chart) in our chart and create secrets and configmaps for oauth2 config and pgpass config. Currently if any of these config is changed, pod is not restarted automatically.
With this MR we can add templated checksum annotations to the pod. So for example we can use these annotations to re-deploy the pod automatically, when oauth2 config or pgpass secret is updated.
I also added checksum of `serverDefinitions` config.
No issues was created.
> [pgadmin4] improve pod annotations to be able to have more checksums

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/templates/deployment.yaml
With the current values it is possible to enable the https in pgadmin container and service. The only problem is that there is no way to configure scheme for probs. This MR make it possible. It also uses `.Values.service.portName ` in various places in deployment definition instead of using hardcoded "http", so it is in sync with service definition.
No issues was created.
> [pgadmin4] make it possible to use  https in container

- charts/pgadmin4/Chart.yaml
This update of pgAdmin4 fixes CVE-2024-2044.
none
> [pgadmin4] Bump appVersion to v8.4

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/deployment.yaml
- charts/pgadmin4/values.yaml
The PR adds support for generic environment variables. This allows retrieving values from Kubernetes Secrets.
N&A
> [pgadmin4] Add support for envVarsExtra

- charts/pgadmin4/Chart.yaml
This update of pgAdmin4 fixes [CVE-2024-2044](https://github.com/advisories/GHSA-27jx-ffw8-xrqv).
none
> [pgadmin4] Bump appVersion to v8.5

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/NOTES.txt
- charts/pgadmin4/templates/_helpers.tpl
- charts/pgadmin4/templates/deployment.yaml
- charts/pgadmin4/templates/server-definitions-configmap.yaml
- charts/pgadmin4/templates/server-definitions-secret.yaml
- charts/pgadmin4/values.yaml
[pgadmin4] Be able to define existingSecret or existingConfigmap containing serverDefinitions
When providing the pgadmin credentials via `.existingSecret`, one is forced to also put server definitions in the exact same secret, if `.serverDefinitions.resourceType` is set to "Secret".
This PR allows users to define a separate secret containing server definitions or to define an external ConfigMap
- fixes #182
- fixes #227
> [pgadmin4] Be able to define existingSecret or existingConfigmap containing serverDefinitions

- charts/pgadmin4/Chart.yaml
This update of pgAdmin4 fixes CVE-2024-4215 and CVE-2024-4216.
none
> [pgadmin4] Bump appVersion to v8.6

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/templates/_helpers.tpl
- charts/pgadmin4/templates/server-definitions-secret.yaml
This PR is an addition to my previous one https://github.com/rowanruseler/helm-charts/pull/249.
It fixes a bug, where the Secret manifest for Server Definitions isn't created, when `.existingSecret` is definied - which is usally the case when credentials are defined in a Secret.
The combination of `.serverDefinitions.resourceType: Secret` and  `.serverDefinitions.servers: {firstServer: ...}` now creates the corresponding secret.
Main issue is the `(not .Values.existingSecret)` [here](https://github.com/rowanruseler/helm-charts/pull/249/commits/829d9f8dfd06654819bfa7cca98adbf3079e3ef1#diff-ad14e1d649548822bbe61b5c1355900ed997f8019c6d4dfbf5c857b828124ff6R1)
> [pgadmin4] fix bug where secret isnt created when using .serverDefinitions.resourceType

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/templates/_helpers.tpl
Pinning the `image.tag` to a specific digest allows full control over what image is actually deployed. But at the moment this breaks the chart because a label must be no more than 63 characters.
This commit resolves:
* rowanruseler/helm-charts/issues/267
> [pgadmin4] Removed image.tag from app.kubernetes.io/version

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/deployment.yaml
- charts/pgadmin4/values.yaml
This allows setting revisionHistoryLimit
Default value is set to 10, which already is the default kubernetes value.
That way we make this change a non-breaking change.
> [pgadmin4] allow setting revisionHistoryLimit

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/examples/serverdefinitions.yaml
- charts/pgadmin4/templates/_helpers.tpl
- charts/pgadmin4/templates/server-definitions-configmap.yaml
- charts/pgadmin4/templates/server-definitions-secret.yaml
- charts/pgadmin4/values.yaml
Because Helm feeds raw YAML to the YAML parser before it ever sees any
Go-template syntax, we need to quote the port part. Else it results in:
```
Error: cannot load values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.example.port":interface {}(nil)}
```
> fix(pgadmin4): correctly handle int and bool value in servers.json

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/README.md
- charts/pgadmin4/templates/_helpers.tpl
- charts/pgadmin4/templates/ingress.yaml
- charts/pgadmin4/values.yaml
* Moved ingress apiVersion logic into _helpers.tpl with stable version check
* Moved ingressClassName and pathType support checks into _helpers.tpl using semverCompare >= 1.18.0
* Updated README.md to reflect changes
* Reverted values.yaml example to use ingressClassName with link to the docs (#288)
> refactor(pgadmin4): move ingress API logic to _helpers.tpl

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/templates/_helpers.tpl
- charts/pgadmin4/values.yaml
previous:
```
containers:
- name: pgadmin4
image: "\ndocker.io/dpage/pgadmin4:9.2"
```
after this commit:
```
containers:
- name: pgadmin4
image: "docker.io/dpage/pgadmin4:9.2"
```
Was pointed out in #293 and #295, thank you very much! Both pull request could not be merged - so quickly made this one to fix it.
> fix(pgadmin4): image parsing bug

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/templates/_helpers.tpl
This PR fixes a type mismatch issue in the pgadmin.image helm template, this should fix #297.
We now use %v instead of %s in printf to properly handle non-string types without introducing extra quotes
> fix(pgadmin4): fix image tag formatting pgadmin.image template

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/templates/NOTES.txt
- charts/pgadmin4/values.yaml
As described in #294, a previous commit removed the default key value. This was a mistake at my end, by trying to force security (and then even removing the wrong default value).
I added the default key back, and added a NOTES.txt security warning message if .env.password is left at SuperSecret
> [pgadmin4] password warning, and existing secret fix

- charts/pgadmin4/Chart.yaml
- charts/pgadmin4/templates/tests/test-connection.yaml
- charts/pgadmin4/values.yaml
Allow user to enable or disable the test feature.
People using gitops principles and/or checking their templated manifest with checkov may want to disable this test pod.
> [pgadmin4] feat: Allow user to enable or disable the test feature
